### ISSUE TITLE
Don't use STDIN if file name is provided even if not a TTY

### ISSUE THREAD

**Issue by felixfbecker** [avantcredit/gql2ts#102]
When running `gql2ts` as part of certain task runners STDIN will not be a TTY.
This causes this code here:

https://github.com/avantcredit/gql2ts/blob/4e36bd52fc81a3c8fbffd5685a0a3933a3474f5b/packages/cli/src/index.ts#L64-L74

to read from STDIN even if a filename is provided, which ultimately will result in the hard-to-debug error
`GraphQLError: Syntax Error GraphQL request (1:1) Unexpected <EOF>`
because the STDIN is empty.

I would propose to always read from file when a file name is given.

**Comment by brettjurgens** [comment]
Makes sense, I'll take a look tomorrow, but doesn't seem too difficult. 

What task runner are you using to do this? Is there a reason not to use the package itself over the cli tool?

**Comment by felixfbecker** [comment]
There's a top level build bash script which eventually calls [goreman](https://github.com/mattn/goreman) to spawn a bunch of concurrent processes, one of which is `npm run watch`, which runs `concurrently` which runs `chokidar schema.graphql -c "gql2ts -o graphqlschema.d.ts schema.graphql"`. This sounds more complicated than it really is and introducing a JS build script would be harder to maintain. I have no idea at what point it breaks down, but I think the proposed fix is reasonable

**Comment by brettjurgens** [comment]
Definitely reasonable, I was just curious what the use case was. Sorry if it came off otherwise

**Comment by felixfbecker** [comment]
not at all :)

**Comment by KaySackey** [comment]
I'll +1 this. I had the same issue running it as a task via Webstorm. It can be worked around by echoing something to the script first, like `echo '' > gql2ts ./gql/schema.json -o ./frontend/gql/schema.ts` , but it'd be better if it didn't block on reading when it doesn't have to.
