### ISSUE TITLE
const enums for enums

### ISSUE THREAD

**Issue by felixfbecker** [avantcredit/gql2ts#107]
It would be awesome if GraphQL enums were converted to `const enum` instead of union types. That way we could write `GitHubGQL.IStatusStateEnum.SUCCESS` as a value instead of `'SUCCESS'`

**Comment by brettjurgens** [comment]
nice idea, let me see if I can get something going

**Comment by brettjurgens** [comment]
@felixfbecker took a while, but #116 implements this and it's out in 1.7.0

**Comment by felixfbecker** [comment]
We needed to revert to non-const enums to support Babel, would it be possible to make this configurable with a flag?
