### ISSUE TITLE
Support Optional Transformations

### ISSUE THREAD

**Issue by brettjurgens** [avantcredit/gql2ts#12]
Should we support transformations?

i.e. running an output through https://github.com/domchristie/humps to camelize?

use case: API returns underscored values, client wants them in camelcase

**Comment by orta** [comment]
This is interesting, when I first tested this out, we went with changing our interfaces to `"{Thing}Type"` instead of `"I{Thing}"`. I think this pattern would work, allowing a user to supply their own `generateInterfaceName`, `generateEnumDeclaration` and `generateEnumName`.

**Comment by brettjurgens** [comment]
i never thought of a good way to do this via the CLI. I think it'd have to be through an API.

otherwise i think we'd have to eval or something, which I'd prefer to avoid

open to any suggestions

**Comment by orta** [comment]
I think it does need evaling and exposing some object, this feels like a common practice ( at least, I got a PR to do it [in Danger](https://github.com/danger/danger-js/pull/71) and I'm using it in React Native to handle TypeScript files.

I guess an alternative is passing in a format string for different ones -> e.g. for generateInterfaceName `"I${name}"`
