### ISSUE TITLE
TypeScript 2.7 breaks cli

### ISSUE THREAD

**Issue by arahansen** [avantcredit/gql2ts#131]
the [typescriptPrettify](https://github.com/avantcredit/gql2ts/blob/master/packages/language-typescript/src/typescriptPrettify.ts#L34) module depends on the `typescript.formatter.RulesProvider` it seems this was removed in a recent release of TypeScript.

Since the CLI pulls this module in, I'm not able to use it on `gql2ts@1.4.0`

`language-typescript` declares its typescript depdency as `^2.2.2` which means it will automatically install 2.7.

I think the version needs to be locked to 2.2.2 (ie, no `^` in the dependency), or the prettifier should be updated to 2.7.

Alternatively, lock typescript to the last working version which seems to be 2.6

**Comment by brettjurgens** [comment]
that's not good, i'll lock the version down in the meantime

**Comment by brettjurgens** [comment]
@arahansen i've just published version 1.4.1. would you mind trying and seeing if it fixes this issue?

**Comment by brettjurgens** [comment]
opened #133 to further the discussion about how to proceed

**Comment by arahansen** [comment]
Changes look good on 1.4.1. Thanks for the fix!
