### ISSUE TITLE
Typescript Formatter

### ISSUE THREAD

**Issue by brettjurgens** [avantcredit/gql2ts#133]
Per #131, typescript has changed their formatting api.

Moving forward, we should find a better option.

Some options of the top of my head:
1. remove formatter from the core language package and continue with the previous "best effort" approach
    - Users might not like the formatting looking weird
    - Faster & cleaner code
    - Current setup allows for user provide their own formatter anyway
1. support the TS2.7 API in addition to the <=2.6 API
    - Requires more code 
    - More brittle, as these are mostly undocumented APIs (pre 2.7 at least)
1. use prettier
    - Best formatting option (in my opinion)
    - Unfortunately, will probably bring in a bunch of new dependencies

Certainly open to other suggestions

**Comment by arahansen** [comment]
Prettier is an excellent tool in my opinion. Since it now has pretty robust TypeScript support, this seems like the winner to me. Which dependencies would need to be taken on besides prettier?

**Comment by brettjurgens** [comment]
@arahansen sorry, what I meant by that is that prettier has a [good amount of dependencies](https://github.com/prettier/prettier/blob/master/package.json#L17-L60) that we'll have to take in.

I completely agree that prettier is awesome, I use it every day 😄, but I'm not sure I want to force users to have it.

I was thinking the default package could do something like

```ts
try {
  const prettier = require('prettier');
  return prettier.format(code);
} catch (e) {
  console.warn('To enable pretty-printing, please install prettier')
  return code;
}
```
