### ISSUE TITLE
graphql should be a peerDependency

### ISSUE THREAD

**Issue by ecwyne** [avantcredit/gql2ts#155]
https://github.com/avantcredit/gql2ts/blob/master/packages/util/package.json#L31

This is causing a second version of `graphql` to be installed in my project. (which doesn't work)

**Comment by brettjurgens** [comment]
@ecwyne why is it causing a second version to be installed? what version are you using?

i made the version range more inclusive yesterday w/ 1.4.4, can you make sure you have that version installed?

**Comment by ecwyne** [comment]
I had `1.5.0` installed. The ranged version (`>= 0.10 <1.0.0`) included my installed version (`0.12.3`) but installing `@gql2ts/from-schema` installed a *separate* version.

I have since discovered your `cli` package and am using that (which avoids installing `@gql2ts/*` in my project at all)

**Comment by ecwyne** [comment]
Because there can only be one version of `graphql` installed, `peerDependencies` seems to be the way everyone is specifying a dependency on `graphql` (though several also have it as a `devDependency` (for testing)

https://github.com/graphql/express-graphql/blob/master/package.json#L96
https://github.com/mickhansen/graphql-sequelize/blob/master/package.json#L50
https://github.com/apollographql/graphql-tools/blob/master/package.json#L58
https://github.com/apollographql/graphql-tag/blob/master/package.json#L34
https://github.com/apollographql/graphql-subscriptions/blob/master/package.json#L14

**Comment by brettjurgens** [comment]
makes sense, i'll open a PR moving it to a peer dependency

**Comment by brettjurgens** [comment]
@ecwyne 1.5.1 has it as a peer dependency
