### ISSUE TITLE
Create new NPM release

### ISSUE THREAD

**Issue by mikfoo** [avantcredit/gql2ts#194]
Now that #192 is merged in, it would be awesome if you could make a new release. 🚀

**Comment by brettjurgens** [comment]
I'm on vacation right now, but I'll see if I can find a way to publish 😁

**Comment by brettjurgens** [comment]
@mikfoo i'm not on my usual machine, so I've published this as a canary (I'll make an official release when I'm back next week). the version is 1.9.0-alpha.5ddac749
