### ISSUE TITLE
Can't figure out how to make this work from the README

### ISSUE THREAD

**Issue by colmartofus** [avantcredit/gql2ts#251]
Note: I'm new to both typescript and graphql.

I couldn't figure it out from the README so I've tried following the medium post:
https://medium.com/@brettjurgens/graphql-typescript-strongly-typed-api-responses-f8aea1e81b93

I ran the following command:
```
gql2ts src/graphql/schema.json -o src/schema.d.ts
```
which generated my file correctly, full of all of the interfaces I want. I just can't seem to use the definitions. In my typescript file I have:
```
// file location: src/Home.tsx

import React, { Component } from 'react';
import 'bootstrap/dist/css/bootstrap.css';
import { createRoom } from './graphql/mutations'
import { API, graphqlOperation } from 'aws-amplify'
import { CreateRoomMutation, Stage } from './API'
//import { IRoom } from './schema'
//import { IRoom } from './schema.d'
```
but when I type `GQL.` I only see my defined enums  (and ModelSortDirection), not `IRoom` or other interface present in `schema.d.ts`. How can I use all of my interfaces? Is there a repo that is a simple example of this working? Thanks.

**Comment by brettjurgens** [comment]
for what it's worth, you probably want to generate the definition based on the query and schema, not just the schema

this might be the readme you're looking for: https://github.com/avantcredit/gql2ts/tree/master/packages/cli

**Comment by colmartofus** [comment]
This looks like what I'm after. Thanks very much.

**Comment by PeteSolid** [comment]
Hi, I generated the schema.d.ts file but how can I import it and use it? I could find no info in the documentation
