### ISSUE TITLE
INode

### ISSUE THREAD

**Issue by valorize** [avantcredit/gql2ts#26]
Hi, first thanks for this repo. It's awesome :D
A problem which I have is that field names may not used in different table more than once. Otherwise I get following warning:
```
Interface 'INode' cannot simultaneously extend types 'IQuery' and 'IMyTable'.
Named property 'title' of types 'IQuery' and 'IMyTable' are not identical.
```
In IQuery is a title function which gives me an MyTable row back but in MyTable itself is a field named title. So `interface INode extends IQuery, IMyTable...` complains.

**Comment by brettjurgens** [comment]
i think this is the same issue as #25 which I just merged 😄 

thanks for the kind words!

**Comment by valorize** [comment]
Wow. Great timing.

**Comment by brettjurgens** [comment]
yep, published in 0.4.0

**Comment by valorize** [comment]
Before 0.4.0 I used `const moduleUtils = require('gql2ts/util/module');` is it replaced by another file?

**Comment by brettjurgens** [comment]
yeah it's now called `gql2ts/util/namespace`, sorry for the trouble. When i moved from modules to namespaces i changed that file (~0.3.0)

**Comment by valorize** [comment]
Ah, easy :D
