### ISSUE TITLE
How to deal with Field Aliases?

### ISSUE THREAD

**Issue by alloy** [avantcredit/gql2ts#33]
In a GraphQL query we can [alias fields](https://github.com/mugli/learning-graphql/blob/master/3.%20Querying%20with%20Field%20Aliases%20and%20Fragments.md), which I’m wondering how one should deal with in TypeScript and a tool like this.

Seeing as it really is related to a _query_, rather than just the schema, I’m thinking that this should be dealt with by implementing something like #30.

The only other issue, in our case, is that we use Relay, so it would be ideal if we could somehow plug into the compiler, extract the query from the Relay fragments, generate the type interfaces, and then actually compile the rest of the file. (This may well be beyond the scope of this tool.)

(Filing this here for visibility, but my colleague @orta said he was going to take a look at this.)

**Comment by brettjurgens** [comment]
i think we'd definitely need #30 to be done for this.

I've been slow to start working on it, but hopefully will find some more time soon.

as far as the relay stuff goes, I've been doing something kind of similar w/ webpack, (generating a `d.ts` for my .graphql queries). at this point it's super basic and doesn't make the interface; just allows the TS compiler to read the files.

whenever #30 gets done I'll probably add that to my webpack loader.

not sure if you guys use webpack, but i'm sure something similar can be done w/ babel

**Comment by alloy** [comment]
I’ve started looking at an implementation for #30, which I’ll use in a VSCode extension that dumps types for Relay fragments in the current file.

**Comment by brettjurgens** [comment]
that'd be pretty sweet, if you get that working opensource it 😄

**Comment by alloy** [comment]
Totally 👍

**Comment by alloy** [comment]
I started looking at this, but it quickly became harder to make it work inside this project rather than standalone (needed TS & GraphQL parsers, plus our needs were around Relay), so in the end I went that route: https://github.com/alloy/relay2ts.

As the name implies, it’s currently tied to Relay, but it should be easy to generalise it to regular GraphQL queries. Let me know if/when you want to take another look at that.

(I’ll leave it to your discretion if you want to leave this ticket open or not.)

**Comment by brettjurgens** [comment]
nice, I'm gonna take a look tonight or tomorrow.

I need to refactor this a bit and after that, maybe it'll be easy to combine the two efforts

**Comment by brettjurgens** [comment]
making some progress in #46

**Comment by brettjurgens** [comment]
@alloy should work now with #46 being merged. install `gql2ts@next` and let me know!

there's a new option to load a query and it will generate the interfaces based on that instead of the whole thing. Because of this, aliases work 👌

**Comment by brettjurgens** [comment]
@alloy this should be fixed in 1.0.0. can you check? i'd like to close this issue if it's all good 😄
