### ISSUE TITLE
Support for schemas by URLs

### ISSUE THREAD

**Issue by CWSpear** [avantcredit/gql2ts#43]
Would you be interested in supporting passing in a URL as opposed to only a filename?

That way, we could do something like:

```
gpl2ts http://example.com/graphql
```

and get our generated types.

https://www.npmjs.com/package/fetch-graphql-schema supports taking a URL and returning JSON, so most of the work is already done.

I'd be willing to do a PR if this was something you were interested in. For now, I can do it in 2 steps (use the mentioned package to create the file, and then pass that file as input), but it'd be a lot nicer in our workflow to not have to create the intermediate file.

**Comment by brettjurgens** [comment]
I'm not opposed to it, should just be a fetch w/ the introspection query.

Another idea could be to support stdin and then the result of the `fetch-graphql-schema` could be piped into gql2ts. That could be potentially useful

**Comment by CWSpear** [comment]
Yeah, that was an option I considered as well. It's one I tried before I checked to see if it was supported (it was not, haha).

**Comment by brettjurgens** [comment]
yeah, i definitely think stdin and stdout could be immensely useful. i'm open to adding fetch support though as well

**Comment by brettjurgens** [comment]
@CWSpear PR for accepting stdin and outputting to stdout: https://github.com/avantcredit/gql2ts/pull/44

**Comment by brettjurgens** [comment]
v0.6.0 will now accept stdin/stdout
