### ISSUE TITLE
Output ES6 module

### ISSUE THREAD

**Issue by danvk** [avantcredit/gql2ts#47]
I'd like to be able to import generated interfaces using ES6 syntax rather than triple-slash references.

This could be as simple as emitting

```ts
declare module 'GQL' { ... }
```

instead of

```ts
declare namespace GQL { ... }
```

**Comment by brettjurgens** [comment]
I've been working on https://github.com/avantcredit/gql2ts/pull/46 recently and i will be adding an option to overwrite default functions (i.e. interface name generation, namespace generation, etc.) to both the new stuff and the old one.

i think the implementation will be like 

```js
/* custom.js */
const generateNamespace = (name, contents) => `declare module '${name}' {
${contents}
}
`;

export default {
  generateNamespace
}
```

and then you run it like

```sh
gql2ts schema.json -o output.d.ts --custom-function-file=./custom.js
```

then gql2ts does something like 

```js
options = DEFAULT_OPTIONS;
if (customFunctionFile) { 
  options = {...options, require(customFunctionFile).default } 
}
```

still thinking it out, but i plan to make more headway on https://github.com/avantcredit/gql2ts/pull/46 this week and hopefully release next week or so

would this work for your use case?

**Comment by danvk** [comment]
Yep, that would do the trick. In the meantime I can work around with:

```
gql2ts schema.json | sed 's/declare namespace GQL/declare module 'schema'/ > declarations/schema.d.ts
```

**Comment by brettjurgens** [comment]
@danvk i just merged #46 and published it on npm as `gql2ts@next`

can you make a file like
```js
// overrides.js
module.exports = {
  default: { 
    generateNamespace: `declare module '${name}' {
${contents}
}
`;
  }
}
```

and run `gql2ts` as `gql2ts {normal parameters} -e ./overrides.js`

and let me know if it works for your use case?

**Comment by zamiang** [comment]
After https://github.com/avantcredit/gql2ts/pull/53 is published to `gql2ts@next`, we can do something more like: (I ran into the same issue as #53 and was about to submit a PR!)

```javascript
// ../../../overrides.js (need to navigate out of the node module)
module.exports = {
  generateNamespace: (name, contents) => (
    `declare module '${name}' {
      ${contents}
    }`)
}
```

**Comment by brettjurgens** [comment]
@zamiang `gql2ts@next` has been updated to 1.0.0-alpha.6 which includes the changes in #53 😃

**Comment by brettjurgens** [comment]
@zamiang published 1.0.0, can i close this issue?

**Comment by zamiang** [comment]
LGTM! Have been using alpha 6 and just switched to 1.0. Confirmed it works as well.

**Comment by brettjurgens** [comment]
awesome 👍
