### ISSUE TITLE
Feature: Add enum support

### ISSUE THREAD

**Issue by davidyaha** [avantcredit/gql2ts#6]
Currently the code does not handle GraphQL Enums. I think the wanted generator is a string literal union.
For example, the following enum:
```graphql
enum UserType {
  ADMIN
  SELLER
  CUSTOMER
}
```

Will become:
```typescript
export type UserType = 'ADMIN' | 'SELLER' | 'CUSTOMER';
```

@brettjurgens  LMK if this a good option in you opinion.

Thanks ahead!

**Comment by brettjurgens** [comment]
I like this idea, I can probably take a look tomorrow at implementing it or would accept a PR!

Been meaning to add some updates for TS2 (adding null types, etc)

**Comment by brettjurgens** [comment]
@davidyaha checkout out v0.2.1, has support for Enums
