### ISSUE TITLE
Lacking input types

### ISSUE THREAD

**Issue by Birowsky** [avantcredit/gql2ts#83]
This is what I get as a type for a query:

```
  interface IQuery {
    __typename: string;
    someQuery: ISomeType | null;
  }
```

Why? Shouldn't I expect this package to generate types for the arguments as well?

**Comment by brettjurgens** [comment]
hi, can you add a reproducible case/what you're doing to get that? 

i think you're using `@gql2ts/from-schema`. I don't think that this generates input types, but it should be trivial to add it

`@gql2ts/from-query` will definitely generate input types for a query

**Comment by Birowsky** [comment]
Sorry, this is the schema I was trying on:
```
schema {
  query: Query
}
type Query {
  someQuery(inputArg:String):Float
}
```
I'm trying to generate types for the server resolvers, so arguments types are essential, don't you think?

**Comment by ecwyne** [comment]
It would be really nice to have argument types generated (on the server for resolvers)

For example:

```graphql
# schema
type Query {
    getPost(postId: String!): Post!
}
type Post {
    id: String!
    body: String!
}
```
I would like (something like) this generated:
```typescript
interface IPost {
    id: string
    body: string
}
interface IQuery {
    __typename: 'Query';
    getPost: IPost | null;
}
interface IQueryGetPostArgs {
    postId: string
}
```
So that I can use them in my resolvers
```typescript
export default {
    Query: {
        getPost: (root: null, args: IQueryGetPostArgs): IPost => {...}
    }
};
```

**Comment by brettjurgens** [comment]
@ecwyne that is related to #59 and #62. I'm going to see if I can get around to this today or tomorrow
