### ISSUE TITLE
TypeError: type.getFields is not a function

### ISSUE THREAD

**Issue by felixfbecker** [avantcredit/gql2ts#85]
Getting this error when running gql2ts from an introspection query:
```js
$ get-graphql-schema http://localhost:3080/.api/graphql --json | gql2ts -o gqlschema.d.ts
/Users/felix/.../node_modules/@gql2ts/from-schema/dist/index.js:123
        const f1 = type.getFields();
                        ^

TypeError: type.getFields is not a function
    at typeToInterface (/Users/felix/.../node_modules/@gql2ts/from-schema/dist/index.js:123:25)
    at typeArr.filter.filter.map.type (/Users/felix/.../node_modules/@gql2ts/from-schema/dist/index.js:159:26)
    at Array.map (native)
    at typesToInterfaces (/Users/felix/.../node_modules/@gql2ts/from-schema/dist/index.js:159:14)
    at run (/Users/felix/.../node_modules/@gql2ts/from-schema/dist/index.js:165:12)
    at Object.exports.schemaToInterfaces (/Users/felix/.../node_modules/@gql2ts/from-schema/dist/index.js:167:73)
    at Object.exports.generateNamespace (/Users/felix/.../node_modules/@gql2ts/from-schema/dist/index.js:170:85)
    at run (/Users/felix/.../node_modules/gql2ts/dist/index.js:39:35)
    at Socket.process.stdin.on (/Users/felix/.../node_modules/gql2ts/dist/index.js:55:35)
    at emitNone (events.js:91:20)
```
This started happening after I added a union type. Could that be related?

**Comment by brettjurgens** [comment]
@felixfbecker hmm, possibly. would you be able to give me a schema to reproduce with?

**Comment by felixfbecker** [comment]
Sure [schema.json.zip](https://github.com/avantcredit/gql2ts/files/1254778/schema.json.zip)

I got it through introspection with https://github.com/graphcool/get-graphql-schema

**Comment by brettjurgens** [comment]
awesome, thanks. taking a look now

**Comment by brettjurgens** [comment]
cool, i've reproduced it. strangely enough it's because the string type is returning false for `instanceof GraphQLScalarType`. 

looking trying to see why this is happening

**Comment by brettjurgens** [comment]
@felixfbecker published 1.1.3, it should be fixed in there!

**Comment by felixfbecker** [comment]
Still happening in 1.2.0 :(
```

> sourcegraph@0.0.1 graphql /Users/felix/...
> get-graphql-schema http://localhost:3080/.api/graphql --json | gql2ts -o gqlschema.d.ts

/Users/felix/.../node_modules/@gql2ts/from-schema/dist/index.js:126
        const f1 = type.getFields();
                        ^

TypeError: type.getFields is not a function
    at typeToInterface (/Users/felix/.../node_modules/@gql2ts/from-schema/dist/index.js:126:25)
    at typeArr.filter.filter.map.type (/Users/felix/.../node_modules/@gql2ts/from-schema/dist/index.js:162:26)
    at Array.map (<anonymous>)
    at typesToInterfaces (/Users/felix/.../node_modules/@gql2ts/from-schema/dist/index.js:162:14)
    at run (/Users/felix/.../node_modules/@gql2ts/from-schema/dist/index.js:168:12)
    at Object.exports.schemaToInterfaces (/Users/felix/.../node_modules/@gql2ts/from-schema/dist/index.js:170:73)
    at Object.exports.generateNamespace (/Users/felix/.../node_modules/@gql2ts/from-schema/dist/index.js:173:85)
    at run (/Users/felix/.../node_modules/gql2ts/dist/index.js:39:35)
    at Socket.process.stdin.on (/Users/felix/.../node_modules/gql2ts/dist/index.js:55:35)
    at emitNone (events.js:110:20)
```

**Comment by brettjurgens** [comment]
weird, i just ran it with the schema.json w/o errors

```sh
 ~/Downloads gql2ts -V
1.2.0
 ~/Downloads cat schema.json | gql2ts -o gqlschema.d.ts
 ~/Downloads 
```

and here's the schema that gets uploaded:
[gqlschema.d.ts.zip](https://github.com/avantcredit/gql2ts/files/1254878/gqlschema.d.ts.zip)

could you check that the version is in fact updated? you can run `gql2ts -V` to get the running version

**Comment by felixfbecker** [comment]
Yeah, checked the version. Weird. Maybe the schema changed? 
[schema.json.zip](https://github.com/avantcredit/gql2ts/files/1254898/schema.json.zip)

**Comment by felixfbecker** [comment]
Appreciate your help!

**Comment by brettjurgens** [comment]
Can you check the version of `@gql2ts/from-schema`? It should also be 1.2.0

**Comment by felixfbecker** [comment]
yup 
```
└─┬ gql2ts@1.2.0
  └── @gql2ts/from-schema@1.2.0
```

**Comment by brettjurgens** [comment]
hmm, the new one is still working for me

just for completeness sake, can you double check that the `package.json` lists 1.2.0 for both modules?

maybe try clearing `node_modules` and reinstalling?

super weird...

**Comment by felixfbecker** [comment]
Hmm, `npm info` doesn't show `@gql2ts/from-query@1.2.0`
```js
19:19 $ npm info @gql2ts/from-query
{ name: '@gql2ts/from-query',
  description: 'generate typescript interfaces from a graphql schema and query',
  'dist-tags':
   { latest: '1.1.2',
     canary: '1.0.2-alpha.50a85222',
     next: '1.0.0-alpha.7' },
  versions:
   [ '0.6.0-alpha.0a7dd353',
     '0.6.0-alpha.113744b9',
     '0.6.0-alpha.52a568e6',
     '0.6.0-alpha.7c8d6c0a',
     '0.6.0-alpha.93b48d62',
     '0.6.0-alpha.a12f0f66',
     '0.6.0-alpha.cca3df5d',
     '1.0.0-alpha.0',
     '1.0.0-alpha.1',
     '1.0.0-alpha.2',
     '1.0.0-alpha.3',
     '1.0.0-alpha.4',
     '1.0.0-alpha.5',
     '1.0.0-alpha.7',
     '1.0.0',
     '1.0.2-alpha.50a85222',
     '1.0.3',
     '1.1.1',
     '1.1.2' ],
```
It's also not listed here: https://www.npmjs.com/package/@gql2ts/from-query

**Comment by felixfbecker** [comment]
Oh sorry, `from-schema`. That's definitely at 1.2.0, checked the package.json

**Comment by felixfbecker** [comment]
Note that the stack trace now has a different line number

**Comment by brettjurgens** [comment]
yep just noticed that, definitely looks like it's the right version.

can you get me the version installed for graphql as well?

**Comment by felixfbecker** [comment]
```
$ npm ls graphql
├─┬ get-graphql-schema@2.1.1
│ └── graphql@0.9.6
└─┬ gql2ts@1.2.0
  └─┬ @gql2ts/util@1.1.2
    └── graphql@0.10.5
```
I confirmed that the packages are correctly exactly as `npm ls` says

**Comment by felixfbecker** [comment]
Does it still work when you install `get-graphql-schema`? That package has a dependency on `graphql@^0.9.1` (which resolves to `0.9.6`), but it seems like `@gql2ts/from-schema` needs `^0.10.1`. The problem is that `@gql2ts/from-schema` doesn't declare this dependency, only `@gql2ts/util`. So `@gql2ts/util` will get its own `node_modules` folder with `graphql@0.10.5`, but `@gql2ts/from-schema` when requiring `graphql` will resolve to the top-level `graphql@0.9.6` installed by `get-graphql-schema`. 

There are a lot of caveats with using `instanceof` with classes from other packages because it will return false for different package versions of the same class. It's better to do other checks, like calling `is*` methods or duck-typing type guards (not sure what is applicable here)

**Comment by brettjurgens** [comment]
yeah, i realized that, so it's not only doing `instanceof`. 

it also checks for the `_scalarConfig` see https://github.com/avantcredit/gql2ts/blob/master/packages/from-schema/src/index.ts#L48

let me see if 0.9.6 has something different i can check for

**Comment by felixfbecker** [comment]
Can't you make sure that it uses the correct graphql version instead? Could you add it as a dependency to from-schema? I feel like any other approach is prone to break again in the future

**Comment by brettjurgens** [comment]
sure that works. seems like the issue is `0.9.x` doesn't support `getFields` on unions, so that's the issue

**Comment by brettjurgens** [comment]
@felixfbecker 1.2.1 has versions pinned

**Comment by felixfbecker** [comment]
awesome, works now! Thanks a lot!
