### ISSUE TITLE
__typename not added to all types

### ISSUE THREAD

**Issue by felixfbecker** [avantcredit/gql2ts#90]
After updating to the latest version, I get this diff on my schema:
```diff
@@ -24,7 +24,7 @@ declare namespace GQL {
   interface IQuery {
     __typename: "Query";
     root: IRoot;
-    node: INode | null;
+    node: Node | null;
   }
 
   /*
@@ -90,6 +90,11 @@ declare namespace GQL {
   /*
     description: null
   */
+  type Node = IRepository | ICommit;
+
+  /*
+    description: null
+  */
   interface INode {
     __typename: "Node";
     id: string;
@@ -320,23 +325,21 @@ declare namespace GQL {
     description: null
   */
   interface ISearchQuery {
-    __typename: "SearchQuery";
     pattern: string;
     isRegExp: boolean;
     isWordMatch: boolean;
     isCaseSensitive: boolean;
     fileMatchLimit: number;
-    includePattern: string | null;
-    excludePattern: string | null;
+    includePattern?: string | null;
+    excludePattern?: string | null;
   }
 
   /*
     description: null
   */
   interface IRepositoryRevision {
-    __typename: "RepositoryRevision";
     repo: string;
-    rev: string | null;
+    rev?: string | null;
   }
```

**Comment by brettjurgens** [comment]
weird... 

other than the `__typename`s, the other changes are expected, right?

just want to make sure before diving in

**Comment by felixfbecker** [comment]
Hmm, not sure. Seems like before the nullable properties were `string | null`, now they are effectively `string | null | undefined`

**Comment by brettjurgens** [comment]
based on the schema.json from the last issue, it looks like SearchQuery is an input object, is that right?

input objects don't have `__typename` (you don't send `__typename` to an input) and nullable properties are `undefined` (i.e. not present on the input)

**Comment by felixfbecker** [comment]
Oh, that makes a lot of sense. So the behaviour was wrong before and is correct in the latest version. Thanks!
