### ISSUE TITLE
Generate typescript types without namespace

### ISSUE THREAD

**Issue by BjornMelgaard** [avantcredit/gql2ts#91]
how to generate ts typings without namespace wrapper? only export each interface

**Comment by brettjurgens** [comment]
you should be able to make a custom language module, see something like:

https://github.com/avantcredit/gql2ts/blob/master/packages/language-typescript/src/index.ts

then just make the namespace generator export only the interfaces

if using the CLI can load the module using with the `-e` option (see https://github.com/avantcredit/gql2ts/tree/master/packages/cli#usage-explanation)

let me know if you run into any issues

**Comment by BjornMelgaard** [comment]
ok, tnx
