### ISSUE TITLE
Update to graphql.js 0.11

### ISSUE THREAD

**Issue by felixfbecker** [avantcredit/gql2ts#92]
Hitting those duplicated module errors again 😞  Updating would solve it 👍

**Comment by brettjurgens** [comment]
👍 i'll take a look

**Comment by adamkl** [comment]
A friend of mine pointed me to [greenkeeper](https://greenkeeper.io) for dealing with issues like this. Free for public repos, might want to take a look.

**Comment by brettjurgens** [comment]
@adamkl yeah [we definitely used to have greenkeeper set up](https://github.com/avantcredit/gql2ts/pulls?q=is%3Apr+is%3Aclosed+label%3Agreenkeeper), but i'm not sure what happened

**Comment by brettjurgens** [comment]
@felixfbecker https://github.com/avantcredit/gql2ts/pull/94

**Comment by brettjurgens** [comment]
fixed in #94
