### ISSUE TITLE
Read schema from .graphql schema file/stdin instead of from JSON

### ISSUE THREAD

**Issue by felixfbecker** [avantcredit/gql2ts#93]
This would be a nice convenience feature.

**Comment by brettjurgens** [comment]
i think that should be easy to support, i'll take a look

**Comment by felixfbecker** [comment]
Did you find a way to do this?

**Comment by brettjurgens** [comment]
i took a look and it should be easy to do from a file, but probably a little more involved for stdin. I'll try to get around to this in the next day or two

**Comment by felixfbecker** [comment]
I personally just need it to be read from file

**Comment by brettjurgens** [comment]
@felixfbecker can you try https://github.com/avantcredit/gql2ts/pull/101
