### ISSUE TITLE
-e flag does not work

### ISSUE THREAD

**Issue by raysuelzer** [avantcredit/gql2ts#98]
There is an error in the genereateNamespace method on 'from-schema' in the Object.assign which causes the external language options to be ignored when an ES module is specificed.

This line of code: 
https://github.com/avantcredit/gql2ts/blob/master/packages/from-schema/src/index.ts#L293

results in an call to Object.assign.  However, due the ES6 module definition you will end up with overrides being something like

```
{
 default: {},
  DEFAULT_OPTIONS {...}
}
```

The code should do something like:
```

export const generateNamespace: GenerateNamespace = (namespace, schema, options = {}, overrides = {}) => {
  const formatters: IFromQueryOptions = { ...DEFAULT_OPTIONS, ...overrides.DEFAULT_OPTIONS };
  return formatters.postProcessor(formatters.generateNamespace(namespace, schemaToInterfaces(schema, options, formatters)));
};
```

The other, perhaps better, option is to change the line in the CLI that calls require to get the 'default' export.

**Comment by raysuelzer** [comment]
Just as an aside, the overrides work fine when using CommonJS modules, but not ES modules, as common JS does not define a 'default'.  So `module.exports = {}` does work to override. `exports.default = {}' does not.

**Comment by brettjurgens** [comment]
ah, looks like it just does a `require` (https://github.com/avantcredit/gql2ts/blob/master/packages/cli/src/index.ts#L34) so it'd make sense that it doesn't work. i can change the docs

**Comment by raysuelzer** [comment]
Thanks!
